import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Header/Navbar";
import Banner from "@/Components/Banner/Banner";
import Services from "@/Components/Services/Services";
import About from "@/Components/About/About";
import CaseStudies from "@/Components/CaseStudies/CaseStudies";
import WorkingProcess from "@/Components/WorkingProcess/WorkingProcess";
import Team from "@/Components/Team/Team";
import Testimonials from "@/Components/Testimonials/Testimonials";
import ContactUs from "@/Components/ContactUs/ContactUs";
import PositiveusFooter from "@/Components/PositiveusFooter/PositiveusFooter";

const inter = Inter({ subsets: ["latin"] });

const space_grotesk_init = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300","400" ,"500","600","700"],
  variable: "--font-space_grotesk"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${space_grotesk_init.variable}`}>
        <div className="xl:w-[1240px] w-full mx-auto xl:px-0 px-5">
        <Navbar />
      <Banner />
      <Services />
      <About />
      <CaseStudies />
      <WorkingProcess />
      <Team />
      <Testimonials />
      <ContactUs />
      <PositiveusFooter />
          {children}
        </div>
      </body>
    </html>
  );
}
